#ifndef _ALTERA_HPS_H_
#define _ALTERA_HPS_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'hps_fpga' in
 * file './hps_fpga.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'fifo_read', class 'altera_avalon_pio'
 * The macros are prefixed with 'FIFO_READ_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_READ_COMPONENT_TYPE altera_avalon_pio
#define FIFO_READ_COMPONENT_NAME fifo_read
#define FIFO_READ_BASE 0x0
#define FIFO_READ_SPAN 32
#define FIFO_READ_END 0x1f
#define FIFO_READ_BIT_CLEARING_EDGE_REGISTER 0
#define FIFO_READ_BIT_MODIFYING_OUTPUT_REGISTER 0
#define FIFO_READ_CAPTURE 0
#define FIFO_READ_DATA_WIDTH 1
#define FIFO_READ_DO_TEST_BENCH_WIRING 0
#define FIFO_READ_DRIVEN_SIM_VALUE 0
#define FIFO_READ_EDGE_TYPE NONE
#define FIFO_READ_FREQ 50000000
#define FIFO_READ_HAS_IN 0
#define FIFO_READ_HAS_OUT 1
#define FIFO_READ_HAS_TRI 0
#define FIFO_READ_IRQ_TYPE NONE
#define FIFO_READ_RESET_VALUE 0

/*
 * Macros for device 'sw', class 'altera_avalon_pio'
 * The macros are prefixed with 'SW_'.
 * The prefix is the slave descriptor.
 */
#define SW_COMPONENT_TYPE altera_avalon_pio
#define SW_COMPONENT_NAME sw
#define SW_BASE 0x0
#define SW_SPAN 32
#define SW_END 0x1f
#define SW_BIT_CLEARING_EDGE_REGISTER 0
#define SW_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SW_CAPTURE 0
#define SW_DATA_WIDTH 10
#define SW_DO_TEST_BENCH_WIRING 0
#define SW_DRIVEN_SIM_VALUE 0
#define SW_EDGE_TYPE NONE
#define SW_FREQ 50000000
#define SW_HAS_IN 1
#define SW_HAS_OUT 0
#define SW_HAS_TRI 0
#define SW_IRQ_TYPE NONE
#define SW_RESET_VALUE 0

/*
 * Macros for device 'fifo_empty', class 'altera_avalon_pio'
 * The macros are prefixed with 'FIFO_EMPTY_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_EMPTY_COMPONENT_TYPE altera_avalon_pio
#define FIFO_EMPTY_COMPONENT_NAME fifo_empty
#define FIFO_EMPTY_BASE 0x10
#define FIFO_EMPTY_SPAN 32
#define FIFO_EMPTY_END 0x2f
#define FIFO_EMPTY_BIT_CLEARING_EDGE_REGISTER 0
#define FIFO_EMPTY_BIT_MODIFYING_OUTPUT_REGISTER 0
#define FIFO_EMPTY_CAPTURE 0
#define FIFO_EMPTY_DATA_WIDTH 1
#define FIFO_EMPTY_DO_TEST_BENCH_WIRING 0
#define FIFO_EMPTY_DRIVEN_SIM_VALUE 0
#define FIFO_EMPTY_EDGE_TYPE NONE
#define FIFO_EMPTY_FREQ 50000000
#define FIFO_EMPTY_HAS_IN 1
#define FIFO_EMPTY_HAS_OUT 0
#define FIFO_EMPTY_HAS_TRI 0
#define FIFO_EMPTY_IRQ_TYPE NONE
#define FIFO_EMPTY_RESET_VALUE 0

/*
 * Macros for device 'led', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_'.
 * The prefix is the slave descriptor.
 */
#define LED_COMPONENT_TYPE altera_avalon_pio
#define LED_COMPONENT_NAME led
#define LED_BASE 0x10
#define LED_SPAN 32
#define LED_END 0x2f
#define LED_BIT_CLEARING_EDGE_REGISTER 0
#define LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_CAPTURE 0
#define LED_DATA_WIDTH 10
#define LED_DO_TEST_BENCH_WIRING 0
#define LED_DRIVEN_SIM_VALUE 0
#define LED_EDGE_TYPE NONE
#define LED_FREQ 50000000
#define LED_HAS_IN 0
#define LED_HAS_OUT 1
#define LED_HAS_TRI 0
#define LED_IRQ_TYPE NONE
#define LED_RESET_VALUE 1023

/*
 * Macros for device 'config_audio', class 'altera_avalon_pio'
 * The macros are prefixed with 'CONFIG_AUDIO_'.
 * The prefix is the slave descriptor.
 */
#define CONFIG_AUDIO_COMPONENT_TYPE altera_avalon_pio
#define CONFIG_AUDIO_COMPONENT_NAME config_audio
#define CONFIG_AUDIO_BASE 0x20
#define CONFIG_AUDIO_SPAN 32
#define CONFIG_AUDIO_END 0x3f
#define CONFIG_AUDIO_BIT_CLEARING_EDGE_REGISTER 0
#define CONFIG_AUDIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CONFIG_AUDIO_CAPTURE 0
#define CONFIG_AUDIO_DATA_WIDTH 10
#define CONFIG_AUDIO_DO_TEST_BENCH_WIRING 0
#define CONFIG_AUDIO_DRIVEN_SIM_VALUE 0
#define CONFIG_AUDIO_EDGE_TYPE NONE
#define CONFIG_AUDIO_FREQ 50000000
#define CONFIG_AUDIO_HAS_IN 0
#define CONFIG_AUDIO_HAS_OUT 1
#define CONFIG_AUDIO_HAS_TRI 0
#define CONFIG_AUDIO_IRQ_TYPE NONE
#define CONFIG_AUDIO_RESET_VALUE 0

/*
 * Macros for device 'audio', class 'altera_avalon_pio'
 * The macros are prefixed with 'AUDIO_'.
 * The prefix is the slave descriptor.
 */
#define AUDIO_COMPONENT_TYPE altera_avalon_pio
#define AUDIO_COMPONENT_NAME audio
#define AUDIO_BASE 0x30
#define AUDIO_SPAN 32
#define AUDIO_END 0x4f
#define AUDIO_BIT_CLEARING_EDGE_REGISTER 0
#define AUDIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define AUDIO_CAPTURE 0
#define AUDIO_DATA_WIDTH 32
#define AUDIO_DO_TEST_BENCH_WIRING 0
#define AUDIO_DRIVEN_SIM_VALUE 0
#define AUDIO_EDGE_TYPE NONE
#define AUDIO_FREQ 50000000
#define AUDIO_HAS_IN 1
#define AUDIO_HAS_OUT 0
#define AUDIO_HAS_TRI 0
#define AUDIO_IRQ_TYPE NONE
#define AUDIO_RESET_VALUE 0

/*
 * Macros for device 'play_d', class 'altera_avalon_pio'
 * The macros are prefixed with 'PLAY_D_'.
 * The prefix is the slave descriptor.
 */
#define PLAY_D_COMPONENT_TYPE altera_avalon_pio
#define PLAY_D_COMPONENT_NAME play_d
#define PLAY_D_BASE 0x30
#define PLAY_D_SPAN 32
#define PLAY_D_END 0x4f
#define PLAY_D_BIT_CLEARING_EDGE_REGISTER 0
#define PLAY_D_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PLAY_D_CAPTURE 0
#define PLAY_D_DATA_WIDTH 1
#define PLAY_D_DO_TEST_BENCH_WIRING 0
#define PLAY_D_DRIVEN_SIM_VALUE 0
#define PLAY_D_EDGE_TYPE NONE
#define PLAY_D_FREQ 50000000
#define PLAY_D_HAS_IN 0
#define PLAY_D_HAS_OUT 1
#define PLAY_D_HAS_TRI 0
#define PLAY_D_IRQ_TYPE NONE
#define PLAY_D_RESET_VALUE 0

/*
 * Macros for device 'key', class 'altera_avalon_pio'
 * The macros are prefixed with 'KEY_'.
 * The prefix is the slave descriptor.
 */
#define KEY_COMPONENT_TYPE altera_avalon_pio
#define KEY_COMPONENT_NAME key
#define KEY_BASE 0x40
#define KEY_SPAN 32
#define KEY_END 0x5f
#define KEY_BIT_CLEARING_EDGE_REGISTER 0
#define KEY_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEY_CAPTURE 0
#define KEY_DATA_WIDTH 4
#define KEY_DO_TEST_BENCH_WIRING 0
#define KEY_DRIVEN_SIM_VALUE 0
#define KEY_EDGE_TYPE NONE
#define KEY_FREQ 50000000
#define KEY_HAS_IN 1
#define KEY_HAS_OUT 0
#define KEY_HAS_TRI 0
#define KEY_IRQ_TYPE NONE
#define KEY_RESET_VALUE 0

/*
 * Macros for device 'record_d', class 'altera_avalon_pio'
 * The macros are prefixed with 'RECORD_D_'.
 * The prefix is the slave descriptor.
 */
#define RECORD_D_COMPONENT_TYPE altera_avalon_pio
#define RECORD_D_COMPONENT_NAME record_d
#define RECORD_D_BASE 0x40
#define RECORD_D_SPAN 32
#define RECORD_D_END 0x5f
#define RECORD_D_BIT_CLEARING_EDGE_REGISTER 0
#define RECORD_D_BIT_MODIFYING_OUTPUT_REGISTER 0
#define RECORD_D_CAPTURE 0
#define RECORD_D_DATA_WIDTH 1
#define RECORD_D_DO_TEST_BENCH_WIRING 0
#define RECORD_D_DRIVEN_SIM_VALUE 0
#define RECORD_D_EDGE_TYPE NONE
#define RECORD_D_FREQ 50000000
#define RECORD_D_HAS_IN 0
#define RECORD_D_HAS_OUT 1
#define RECORD_D_HAS_TRI 0
#define RECORD_D_IRQ_TYPE NONE
#define RECORD_D_RESET_VALUE 0


#endif /* _ALTERA_HPS_H_ */
