// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 15.0 (Build Build 145 04/22/2015)
// Created on Thu Apr 21 10:32:41 2016

syn_fifo syn_fifo_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst(rst_sig) ,	// input  rst_sig
	.wr_cs(wr_cs_sig) ,	// input  wr_cs_sig
	.rd_cs(rd_cs_sig) ,	// input  rd_cs_sig
	.data_in(data_in_sig) ,	// input [DATA_WIDTH-1:0] data_in_sig
	.rd_en(rd_en_sig) ,	// input  rd_en_sig
	.wr_en(wr_en_sig) ,	// input  wr_en_sig
	.data_out(data_out_sig) ,	// output [DATA_WIDTH-1:0] data_out_sig
	.empty(empty_sig) ,	// output  empty_sig
	.full(full_sig) 	// output  full_sig
);

defparam syn_fifo_inst.DATA_WIDTH = 16;
defparam syn_fifo_inst.ADDR_WIDTH = 16;
//defparam syn_fifo_inst.RAM_DEPTH = ;
