// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 15.0 (Build Build 145 04/22/2015)
// Created on Mon Apr 25 10:23:40 2016

async_trap_and_reset async_trap_and_reset_inst
(
	.async_sig(async_sig_sig) ,	// input  async_sig_sig
	.outclk(outclk_sig) ,	// input  outclk_sig
	.out_sync_sig(out_sync_sig_sig) ,	// output  out_sync_sig_sig
	.auto_reset(auto_reset_sig) ,	// input  auto_reset_sig
	.reset(reset_sig) 	// input  reset_sig
);

