// Copyright (C) 1991-2014 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 14.1 (Build Build 186 12/03/2014)
// Created on Mon Aug 17 16:24:14 2015

clk_18_4 clk_18_4_inst
(
	.refclk(refclk_sig) ,	// input  refclk_sig
	.rst(rst_sig) ,	// input  rst_sig
	.outclk_0(outclk_0_sig) ,	// output  outclk_0_sig
	.locked(locked_sig) 	// output  locked_sig
);

